export const CITY_COUNTRY_OPTIONS = [
  "Amsterdam, Netherlands",
  "Athens, Greece",
  "Auckland, New Zealand",
  "Austin, United States",
  "Bangkok, Thailand",
  "Barcelona, Spain",
  "Beijing, China",
  "Beirut, Lebanon",
  "Belgrade, Serbia",
  "Berlin, Germany",
  "Bogota, Colombia",
  "Boston, United States",
  "Bratislava, Slovakia",
  "Brisbane, Australia",
  "Brussels, Belgium",
  "Bucharest, Romania",
  "Budapest, Hungary",
  "Buenos Aires, Argentina",
  "Cairo, Egypt",
  "Calgary, Canada",
  "Cape Town, South Africa",
  "Cartagena, Colombia",
  "Casablanca, Morocco",
  "Chicago, United States",
  "Christchurch, New Zealand",
  "Copenhagen, Denmark",
  "Cusco, Peru",
  "Dallas, United States",
  "Delhi, India",
  "Doha, Qatar",
  "Dubai, United Arab Emirates",
  "Dublin, Ireland",
  "Edinburgh, United Kingdom",
  "Florence, Italy",
  "Frankfurt, Germany",
  "Fukuoka, Japan",
  "Geneva, Switzerland",
  "Glasgow, United Kingdom",
  "Guadalajara, Mexico",
  "Guangzhou, China",
  "Hanoi, Vietnam",
  "Havana, Cuba",
  "Helsinki, Finland",
  "Ho Chi Minh City, Vietnam",
  "Hong Kong, China",
  "Honolulu, United States",
  "Houston, United States",
  "Istanbul, Turkey",
  "Jakarta, Indonesia",
  "Johannesburg, South Africa",
  "Krakow, Poland",
  "Kuala Lumpur, Malaysia",
  "Kyoto, Japan",
  "Lagos, Nigeria",
  "Las Vegas, United States",
  "Lima, Peru",
  "Lisbon, Portugal",
  "Ljubljana, Slovenia",
  "London, United Kingdom",
  "Los Angeles, United States",
  "Lyon, France",
  "Madrid, Spain",
  "Manila, Philippines",
  "Marrakesh, Morocco",
  "Melbourne, Australia",
  "Mexico City, Mexico",
  "Miami, United States",
  "Milan, Italy",
  "Montreal, Canada",
  "Moscow, Russia",
  "Mumbai, India",
  "Munich, Germany",
  "Nairobi, Kenya",
  "Naples, Italy",
  "New Orleans, United States",
  "New York, United States",
  "Nice, France",
  "Osaka, Japan",
  "Oslo, Norway",
  "Ottawa, Canada",
  "Palermo, Italy",
  "Panama City, Panama",
  "Paris, France",
  "Perth, Australia",
  "Phnom Penh, Cambodia",
  "Portland, United States",
  "Porto, Portugal",
  "Prague, Czechia",
  "Pune, India",
  "Quebec City, Canada",
  "Reykjavik, Iceland",
  "Rio de Janeiro, Brazil",
  "Riyadh, Saudi Arabia",
  "Rome, Italy",
  "Rotterdam, Netherlands",
  "Salzburg, Austria",
  "San Diego, United States",
  "San Francisco, United States",
  "San Jose, Costa Rica",
  "Santiago, Chile",
  "Santo Domingo, Dominican Republic",
  "Sao Paulo, Brazil",
  "Seattle, United States",
  "Seoul, South Korea",
  "Shanghai, China",
  "Singapore, Singapore",
  "Sofia, Bulgaria",
  "Stockholm, Sweden",
  "Stuttgart, Germany",
  "Sydney, Australia",
  "Taipei, Taiwan",
  "Tallinn, Estonia",
  "Tampa, United States",
  "Tbilisi, Georgia",
  "Tehran, Iran",
  "Tel Aviv, Israel",
  "The Hague, Netherlands",
  "Tokyo, Japan",
  "Toronto, Canada",
  "Toulouse, France",
  "Valencia, Spain",
  "Vancouver, Canada",
  "Venice, Italy",
  "Vienna, Austria",
  "Warsaw, Poland",
  "Washington, D.C., United States",
  "Wellington, New Zealand",
  "Winnipeg, Canada",
  "Wroclaw, Poland",
  "Xi'an, China",
  "Yerevan, Armenia",
  "Zagreb, Croatia",
  "Zurich, Switzerland",
] as const;
